### ISSUE TITLE
ModuleNotFoundError for Cyberpunk GLTF Material plugin

### ISSUE THREAD

**Issue by Chanka0** [HitmanHimself/cp77research#11]
Error occurs when attempting to enable the Cyberpunk GLTF Material plugin in Blender.
This error occurs on Blender versions 2.92, 2.93, and 3.0.
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\__init__.py", line 18, in <module>
    from .material_types.multilayer import Multilayered
ModuleNotFoundError: No module named 'i_scene_cp77_gltf.material_types.multilayer'
```

**Comment by Chanka0** [comment]
Issue is that the modules have been renamed with different capitalization. Was able to fix it myself by editing `__init__.py`  and `setup.py`

**Comment by Chanka0** [comment]
Encountered new issue.

```
Python: Traceback (most recent call last):
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\__init__.py", line 79, in execute
    bpymat = Builder.create(index)
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\main\setup.py", line 31, in create
    multilayered.create(rawMat["Data"],bpyMat)
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 549, in create
    self.createLayerMaterial(os.path.basename(Data["MultilayerSetup"])[:-8]+"_Layer_",LayerCount,CurMat,Data["MultilayerMask"],Data["GlobalNormal"])
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 272, in createLayerMaterial
    yoink = self.setGlobNormal(normalimgpath,CurMat,CurMat.nodes["Layer_"+str(LayerCount-2)].outputs[1])
  File "C:\Users\Chanka\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\i_scene_cp77_gltf\material_types\multilayered.py", line 154, in setGlobNormal
    GNMap = CreateShaderNodeNormalMap(CurMat,self.BasePath + normalimgpath,-600,-550,'GlobalNormal',self.image_format)
NameError: name 'CreateShaderNodeNormalMap' is not defined

location: <unknown location>:-1
```
